# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
try:
    from PyQt5 import QtCore, QtGui, QtWidgets
except:
    os.system("python -m pip install PyQt5")
    
from PyQt5 import QtCore, QtGui, QtWidgets
import SiL
import QuickADB

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(309, 250)
        self.ADBCheck = QtWidgets.QPushButton(Dialog)
        self.ADBCheck.setGeometry(QtCore.QRect(10, 10, 141, 51))
        self.ADBCheck.setObjectName("ADBCheck")
        self.ADBCheck.clicked.connect(QuickADB.ADBchk)

        self.Sideload = QtWidgets.QPushButton(Dialog)
        self.Sideload.setGeometry(QtCore.QRect(160, 10, 141, 51))
        self.Sideload.setObjectName("Sideload")
        self.Sideload.clicked.connect(self.calling_sil)

        self.Fastboot = QtWidgets.QPushButton(Dialog)
        self.Fastboot.setGeometry(QtCore.QRect(10, 130, 141, 51))
        self.Fastboot.setObjectName("Fastboot")
        self.Fastboot.clicked.connect(QuickADB.Fastboot)

        self.Recovery = QtWidgets.QPushButton(Dialog)
        self.Recovery.setGeometry(QtCore.QRect(10, 190, 141, 51))
        self.Recovery.setObjectName("Recovery")
        self.Recovery.clicked.connect(QuickADB.Recovery)

        self.Shutdown = QtWidgets.QPushButton(Dialog)
        self.Shutdown.setGeometry(QtCore.QRect(160, 190, 141, 51))
        self.Shutdown.setObjectName("Shutdown")
        self.Shutdown.clicked.connect(QuickADB.Shutdown)

        self.reboot = QtWidgets.QPushButton(Dialog)
        self.reboot.setGeometry(QtCore.QRect(10, 70, 141, 51))
        self.reboot.setObjectName("reboot")
        self.reboot.clicked.connect(QuickADB.reboot)

        self.install = QtWidgets.QPushButton(Dialog)
        self.install.setGeometry(QtCore.QRect(160, 70, 141, 51))
        self.install.setObjectName("install")
        self.install.clicked.connect(self.calling_ins)
        '''
        self.per = QtWidgets.QPushButton(Dialog)
        self.per.setGeometry(QtCore.QRect(160, 130, 141, 51))
        self.per.setObjectName("per")
        '''
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "QuickADB"))
        self.ADBCheck.setText(_translate("Dialog", "ADB 檢測連接"))
        self.Sideload.setText(_translate("Dialog", "sideload 側載"))
        self.Fastboot.setText(_translate("Dialog", "重新啟動進入Fastboot"))
        self.Recovery.setText(_translate("Dialog", "重新啟動進入Recovery"))
        self.Shutdown.setText(_translate("Dialog", "關機"))
        self.reboot.setText(_translate("Dialog", "重新啟動"))
        self.install.setText(_translate("Dialog", "安裝APK"))
        '''
        self.per.setText(_translate("Dialog", "給予應用程式權限"))
        '''
    def calling_sil(self):
        os.system("python.exe SiL.py")

    def calling_ins(self):
        os.system("python.exe ins.py")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
